version = 1
SPDX-PackageName = "coldfront"
SPDX-PackageDownloadLocation = "https://github.com/ubccr/coldfront"

[[annotations]]
path = [
    ".python-version",
    "Dockerfile",
    ".dockerignore",
    "MANIFEST.in",
    "docs/pages/.pages",
    "pyproject.toml",
    "**.yaml",
    "**.yml",
    "**.md",
    "**.txt",
    "**.csv",
    "**.sql",
    "**.gitignore",
    "**.html",
    "**.css",
    "**.scss",
    "**.js",
    "**.ts",
    "**.webmanifest",
]
SPDX-FileCopyrightText = "(C) ColdFront Authors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "docs/pages/images/*",
    "docs/pages/assets/*",
    "**.ico",
]
SPDX-FileCopyrightText = "(C) ColdFront Authors"
SPDX-License-Identifier = "CC-BY-NC-ND-4.0"

[[annotations]]
path = [
    "uv.lock",
    "coldfront/static/package-lock.json",
    "coldfront/static/bundles/manifest.json",
    "coldfront/static/package.json",
    "coldfront/static/tsconfig.json",
    "coldfront/static/.prettierignore",
    "coldfront/static/.prettierrc",
    "coldfront/**.png",
    "coldfront/**.jpg",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "coldfront/static/bundles/fa-*.woff2",
]
SPDX-FileCopyrightText = "Copyright (c) 2011-2025 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "coldfront/static/bundles/c3.js",
]
SPDX-FileCopyrightText = "Copyright (c) 2013 Masayuki Tanaka"
SPDX-License-Identifier = "MIT"
