name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        node-version: ["24.x"]
    env:
      PLUGIN_API: true
      DJANGO_VITE_DEV_MODE: true

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the project
        run: uv sync --locked --dev

      - name: Install frontend packages
        run: npm --prefix coldfront/static install

      - name: Check for lint violations
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check

      - name: Check frontend with eslint and prettier
        run: npm --prefix coldfront/static run check

      - name: Compile and bundle frontend static assets
        run: npm --prefix coldfront/static run build

      - name: Check bundled frontend static assets have been commited
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Error: pre-compiled bundled frontend static assets have not been committed"
            git status
            exit 1
          else
            echo "Bundled frontend static assets check passed."
          fi

      - name: Check licence with reuse
        run: uv run reuse lint

      - name: Run tests
        run: uv run coldfront test

      - name: Check for migrations
        run: uv run coldfront makemigrations --check
